/**
 * WordPress dependencies
 */
import { __ } from "@wordpress/i18n";
import {
	addCard,
	addSubmenu,
	alignCenter,
	alignJustify,
	alignLeft,
	alignNone,
	alignRight,
	archive,
	arrowDown,
	arrowLeft,
	arrowRight,
	arrowUp,
	atSymbol,
	aspectRatio,
	audio,
	backup,
	blockDefault,
	blockTable,
	box,
	brush,
	bug,
	button,
	buttons,
	calendar,
	cancelCircleFilled,
	capturePhoto,
	captureVideo,
	category,
	chartBar,
	check,
	chevronDown,
	chevronLeft,
	chevronRight,
	chevronRightSmall,
	chevronUp,
	classic,
	close,
	closeSmall,
	cloudUpload,
	cloud,
	code,
	cog,
	color,
	column,
	columns,
	comment,
	commentAuthorAvatar,
	commentAuthorName,
	commentContent,
	// commentEditLink, the WP Icons NPM package does not yet include this icon.
	commentReplyLink,
	cover,
	create,
	crop,
	currencyDollar,
	currencyEuro,
	currencyPound,
	customPostType,
	desktop,
	dragHandle,
	download,
	edit,
	external,
	file,
	flipHorizontal,
	flipVertical,
	formatBold,
	formatCapitalize,
	formatIndent,
	formatIndentRTL,
	formatItalic,
	formatListBullets,
	formatListBulletsRTL,
	formatListNumbered,
	formatListNumberedRTL,
	formatLtr,
	formatLowercase,
	formatOutdent,
	formatOutdentRTL,
	formatRtl,
	formatStrikethrough,
	formatUnderline,
	formatUppercase,
	fullscreen,
	gallery,
	globe,
	grid,
	group,
	handle,
	heading,
	help,
	helpFilled,
	inbox,
	institution,
	home,
	html,
	image,
	info,
	insertAfter,
	insertBefore,
	justifyLeft,
	justifyCenter,
	justifyRight,
	justifySpaceBetween,
	key,
	keyboardClose,
	keyboardReturn,
	layout,
	lifesaver,
	// There are some issues with these icons.
	// lineDashed,
	// lineDotted,
	// lineSolid,
	link,
	linkOff,
	list,
	listView,
	lock,
	login,
	loop,
	mapMarker,
	media,
	mediaAndText,
	megaphone,
	menu,
	mobile,
	more,
	moreHorizontal,
	moreHorizontalMobile,
	moreVertical,
	moveTo,
	navigation,
	overlayText,
	pageBreak,
	customLink,
	page,
	pages,
	paragraph,
	payment,
	percent,
	positionCenter,
	positionLeft,
	positionRight,
	pencil,
	people,
	pin,
	plugins,
	plusCircleFilled,
	plusCircle,
	plus,
	post,
	postAuthor,
	postCategories,
	postContent,
	postComments,
	postCommentsCount,
	postCommentsForm,
	postDate,
	postExcerpt,
	postFeaturedImage,
	postList,
	postTerms,
	previous,
	next,
	preformatted,
	pullLeft,
	pullRight,
	pullquote,
	queryPagination,
	queryPaginationNext,
	queryPaginationNumbers,
	queryPaginationPrevious,
	quote,
	receipt,
	redo,
	removeBug,
	removeSubmenu,
	replace,
	reset,
	resizeCornerNE,
	reusableBlock,
	rotateLeft,
	rotateRight,
	row,
	rss,
	search,
	separator,
	settings,
	share,
	shield,
	shortcode,
	siteLogo,
	stack,
	starEmpty,
	starFilled,
	starHalf,
	store,
	stretchFullWidth,
	styles,
	shipping,
	stretchWide,
	subscript,
	superscript,
	swatch,
	symbol,
	symbolFilled,
	tableColumnAfter,
	tableColumnBefore,
	tableColumnDelete,
	tableRowAfter,
	tableRowBefore,
	tableRowDelete,
	table,
	tag,
	termDescription,
	footer,
	header,
	sidebar,
	textColor,
	tablet,
	tip,
	title,
	tool,
	trash,
	trendingDown,
	trendingUp,
	typography,
	undo,
	ungroup,
	unlock,
	update,
	upload,
	verse,
	video,
	warning,
	widget,
} from "@wordpress/icons";

/**
 * Internal dependencies
 */
import {
	amazon,
	bandcamp,
	behance,
	chain,
	codepen,
	deviantart,
	dribbble,
	dropbox,
	etsy,
	facebook,
	feed,
	fivehundredpx,
	flickr,
	foursquare,
	goodreads,
	google,
	github,
	instagram,
	lastfm,
	linkedin,
	mail,
	mastodon,
	meetup,
	medium,
	patreon,
	pinterest,
	pocket,
	redditSolid,
	reddit,
	skype,
	snapchat,
	soundcloud,
	spotify,
	telegram,
	tiktok,
	tumblr,
	twitch,
	twitter,
	vimeo,
	vk,
	wordpress,
	yelp,
	youtube,
} from "./wordpress/social";
import { fontAwesomeCategories, fontAwesomeIcons } from "./font-awesome";

// Temporary icon specifications that are not yet in the NPM package.
import { commentEditLink, sparkles } from "./wordpress/temp";

const wordpressSocialIcons = [
	{
		isDefault: true,
		name: "wordpress",
		title: "WordPress",
		type: "wordpress",
		icon: wordpress,
		categories: ["logos"],
	},
	{
		name: "fivehundredpx",
		title: "500px",
		type: "wordpress",
		icon: fivehundredpx,
		categories: ["logos"],
	},
	{
		name: "amazon",
		title: "Amazon",
		type: "wordpress",
		icon: amazon,
		categories: ["logos"],
	},
	{
		name: "bandcamp",
		title: "Bandcamp",
		type: "wordpress",
		icon: bandcamp,
		categories: ["logos"],
	},
	{
		name: "behance",
		title: "Behance",
		type: "wordpress",
		icon: behance,
		categories: ["logos"],
	},
	{
		name: "chain",
		title: "Link",
		type: "wordpress",
		icon: chain,
	},
	{
		name: "codepen",
		title: "CodePen",
		type: "wordpress",
		icon: codepen,
		categories: ["logos"],
	},
	{
		name: "deviantart",
		title: "DeviantArt",
		type: "wordpress",
		icon: deviantart,
		categories: ["logos"],
	},
	{
		name: "dribbble",
		title: "Dribbble",
		type: "wordpress",
		icon: dribbble,
		categories: ["logos"],
	},
	{
		name: "dropbox",
		title: "Dropbox",
		type: "wordpress",
		icon: dropbox,
		categories: ["logos"],
	},
	{
		name: "etsy",
		title: "Etsy",
		type: "wordpress",
		icon: etsy,
		categories: ["logos"],
	},
	{
		name: "facebook",
		title: "Facebook",
		type: "wordpress",
		icon: facebook,
		categories: ["logos"],
	},
	{
		name: "feed",
		title: "RSS Feed",
		type: "wordpress",
		icon: feed,
		categories: ["logos"],
	},
	{
		name: "flickr",
		title: "Flickr",
		type: "wordpress",
		icon: flickr,
		categories: ["logos"],
	},
	{
		name: "foursquare",
		title: "Foursquare",
		type: "wordpress",
		icon: foursquare,
		categories: ["logos"],
	},
	{
		name: "goodreads",
		title: "Goodreads",
		type: "wordpress",
		icon: goodreads,
		categories: ["logos"],
	},
	{
		name: "google",
		title: "Google",
		type: "wordpress",
		icon: google,
		categories: ["logos"],
	},
	{
		name: "github",
		title: "GitHub",
		type: "wordpress",
		icon: github,
		categories: ["logos"],
	},
	{
		name: "instagram",
		title: "Instagram",
		type: "wordpress",
		icon: instagram,
		categories: ["logos"],
	},
	{
		name: "lastfm",
		title: "Last.fm",
		type: "wordpress",
		icon: lastfm,
		categories: ["logos"],
	},
	{
		name: "linkedin",
		title: "LinkedIn",
		type: "wordpress",
		icon: linkedin,
		categories: ["logos"],
	},
	{
		name: "mail",
		title: "Mail",
		categories: ["email", "e-mail"],
		type: "wordpress",
		icon: mail,
	},
	{
		name: "mastodon",
		title: "Mastodon",
		type: "wordpress",
		icon: mastodon,
		categories: ["logos"],
	},
	{
		name: "meetup",
		title: "Meetup",
		type: "wordpress",
		icon: meetup,
		categories: ["logos"],
	},
	{
		name: "medium",
		title: "Medium",
		type: "wordpress",
		icon: medium,
		categories: ["logos"],
	},
	{
		name: "patreon",
		title: "Patreon",
		type: "wordpress",
		icon: patreon,
		categories: ["logos"],
	},
	{
		name: "pinterest",
		title: "Pinterest",
		type: "wordpress",
		icon: pinterest,
		categories: ["logos"],
	},
	{
		name: "pocket",
		title: "Pocket",
		type: "wordpress",
		icon: pocket,
		categories: ["logos"],
	},
	{
		name: "reddit-solid",
		title: "Reddit Solid",
		type: "wordpress",
		icon: redditSolid,
		categories: ["logos"],
	},
	{
		name: "reddit",
		title: "Reddit",
		type: "wordpress",
		icon: reddit,
		categories: ["logos"],
	},
	{
		name: "skype",
		title: "Skype",
		type: "wordpress",
		icon: skype,
		categories: ["logos"],
	},
	{
		name: "snapchat",
		title: "Snapchat",
		type: "wordpress",
		icon: snapchat,
		categories: ["logos"],
	},
	{
		name: "soundcloud",
		title: "SoundCloud",
		type: "wordpress",
		icon: soundcloud,
		categories: ["logos"],
	},
	{
		name: "spotify",
		title: "Spotify",
		type: "wordpress",
		icon: spotify,
		categories: ["logos"],
	},
	{
		name: "telegram",
		title: "Telegram",
		type: "wordpress",
		icon: telegram,
		categories: ["logos"],
	},
	{
		name: "tiktok",
		title: "TikTok",
		type: "wordpress",
		icon: tiktok,
		categories: ["logos"],
	},
	{
		name: "tumblr",
		title: "Tumblr",
		type: "wordpress",
		icon: tumblr,
		categories: ["logos"],
	},
	{
		name: "twitch",
		title: "Twitch",
		type: "wordpress",
		icon: twitch,
		categories: ["logos"],
	},
	{
		isDefault: true,
		name: "twitter",
		title: "Twitter",
		type: "wordpress",
		icon: twitter,
		categories: ["logos"],
	},
	{
		name: "vimeo",
		title: "Vimeo",
		type: "wordpress",
		icon: vimeo,
		categories: ["logos"],
	},
	{
		name: "vk",
		title: "VK",
		type: "wordpress",
		icon: vk,
		categories: ["logos"],
	},
	{
		name: "yelp",
		title: "Yelp",
		type: "wordpress",
		icon: yelp,
		categories: ["logos"],
	},
	{
		name: "youtube",
		title: "YouTube",
		type: "wordpress",
		icon: youtube,
		categories: ["logos"],
	},
];

const wordpressIcons = [
	{
		name: "addCard",
		title: __("Add Card", "ultimate-blocks"),
		type: "wordpress",
		icon: addCard,
	},
	{
		name: "addSubmenu",
		title: __("Add Submenu", "ultimate-blocks"),
		type: "wordpress",
		icon: addSubmenu,
		categories: ["arrows"],
	},
	{
		name: "alignCenter",
		title: __("Align Center", "ultimate-blocks"),
		type: "wordpress",
		icon: alignCenter,
		categories: ["editor"],
	},
	{
		name: "alignJustify",
		title: __("Align Justify", "ultimate-blocks"),
		type: "wordpress",
		icon: alignJustify,
		categories: ["editor"],
	},
	{
		name: "alignLeft",
		title: __("Align Left", "ultimate-blocks"),
		type: "wordpress",
		icon: alignLeft,
		categories: ["editor"],
	},
	{
		name: "alignNone",
		title: __("Align None", "ultimate-blocks"),
		type: "wordpress",
		icon: alignNone,
		categories: ["editor"],
	},
	{
		name: "alignRight",
		title: __("Align Right", "ultimate-blocks"),
		type: "wordpress",
		icon: alignRight,
		categories: ["editor"],
	},
	{
		name: "archive",
		title: __("Archive", "ultimate-blocks"),
		type: "wordpress",
		icon: archive,
		categories: ["blocks"],
	},
	{
		name: "arrowDown",
		title: __("Arrow Down", "ultimate-blocks"),
		type: "wordpress",
		icon: arrowDown,
		categories: ["arrows"],
	},
	{
		name: "arrowLeft",
		title: __("Arrow Left", "ultimate-blocks"),
		type: "wordpress",
		icon: arrowLeft,
		categories: ["arrows"],
	},
	{
		name: "arrowRight",
		title: __("Arrow Right", "ultimate-blocks"),
		type: "wordpress",
		icon: arrowRight,
		categories: ["arrows"],
	},
	{
		name: "arrowUp",
		title: __("Arrow Up", "ultimate-blocks"),
		type: "wordpress",
		icon: arrowUp,
		categories: ["arrows"],
	},
	{
		name: "atSymbol",
		title: __("At Symbol", "ultimate-blocks"),
		type: "wordpress",
		icon: atSymbol,
	},
	{
		name: "aspectRatio",
		title: __("Aspect Ratio", "ultimate-blocks"),
		type: "wordpress",
		icon: aspectRatio,
		categories: ["media"],
	},
	{
		name: "audio",
		title: __("Audio", "ultimate-blocks"),
		type: "wordpress",
		icon: audio,
		categories: ["media"],
	},
	{
		name: "backup",
		title: __("Backup", "ultimate-blocks"),
		type: "wordpress",
		icon: backup,
	},
	{
		name: "blockDefault",
		title: __("Block Default", "ultimate-blocks"),
		type: "wordpress",
		icon: blockDefault,
		categories: ["blocks"],
	},
	{
		name: "blockTable",
		title: __("Block Table", "ultimate-blocks"),
		type: "wordpress",
		icon: blockTable,
	},
	{
		name: "box",
		title: __("Box", "ultimate-blocks"),
		type: "wordpress",
		icon: box,
	},
	{
		name: "brush",
		title: __("Brush", "ultimate-blocks"),
		type: "wordpress",
		icon: brush,
	},
	{
		name: "bug",
		title: __("Bug", "ultimate-blocks"),
		type: "wordpress",
		icon: bug,
	},
	{
		name: "button",
		title: __("Button", "ultimate-blocks"),
		type: "wordpress",
		icon: button,
		categories: ["blocks"],
	},
	{
		name: "buttons",
		title: __("Buttons", "ultimate-blocks"),
		type: "wordpress",
		icon: buttons,
		categories: ["blocks"],
	},
	{
		name: "calendar",
		title: __("Calendar", "ultimate-blocks"),
		type: "wordpress",
		icon: calendar,
		categories: ["blocks"],
	},
	{
		name: "cancelCircleFilled",
		title: __("Cancel - Circle Filled", "ultimate-blocks"),
		type: "wordpress",
		icon: cancelCircleFilled,
	},
	{
		name: "capturePhoto",
		title: __("Capture Photo", "ultimate-blocks"),
		type: "wordpress",
		icon: capturePhoto,
		categories: ["media"],
	},
	{
		name: "captureVideo",
		title: __("Capture Video", "ultimate-blocks"),
		type: "wordpress",
		icon: captureVideo,
		categories: ["media"],
	},
	{
		name: "category",
		title: __("Category", "ultimate-blocks"),
		type: "wordpress",
		icon: category,
		categories: ["blocks"],
	},
	{
		name: "chartBar",
		title: __("Chart Bar", "ultimate-blocks"),
		type: "wordpress",
		icon: chartBar,
	},
	{
		name: "check",
		title: __("Check", "ultimate-blocks"),
		type: "wordpress",
		icon: check,
	},
	{
		name: "chevronDown",
		title: __("Chevron Down", "ultimate-blocks"),
		type: "wordpress",
		icon: chevronDown,
		categories: ["arrows"],
	},
	{
		name: "chevronLeft",
		title: __("Chevron Left", "ultimate-blocks"),
		type: "wordpress",
		icon: chevronLeft,
		categories: ["arrows"],
	},
	{
		name: "chevronRight",
		title: __("Chevron Right", "ultimate-blocks"),
		type: "wordpress",
		icon: chevronRight,
		categories: ["arrows"],
	},
	{
		name: "chevronRightSmall",
		title: __("Chevron Right - Small", "ultimate-blocks"),
		type: "wordpress",
		icon: chevronRightSmall,
		categories: ["arrows"],
	},
	{
		name: "chevronUp",
		title: __("Chevron Up", "ultimate-blocks"),
		type: "wordpress",
		icon: chevronUp,
		categories: ["arrows"],
	},
	{
		name: "classic",
		title: __("Classic", "ultimate-blocks"),
		type: "wordpress",
		icon: classic,
		categories: ["blocks"],
	},
	{
		name: "close",
		title: __("Close", "ultimate-blocks"),
		type: "wordpress",
		icon: close,
	},
	{
		name: "closeSmall",
		title: __("Close - Small", "ultimate-blocks"),
		type: "wordpress",
		icon: closeSmall,
	},
	{
		name: "cloudUpload",
		title: __("Cloud Upload", "ultimate-blocks"),
		type: "wordpress",
		icon: cloudUpload,
		categories: ["arrows"],
	},
	{
		name: "cloud",
		title: __("Cloud", "ultimate-blocks"),
		type: "wordpress",
		icon: cloud,
	},
	{
		name: "code",
		title: __("Code", "ultimate-blocks"),
		type: "wordpress",
		icon: code,
		categories: ["blocks"],
	},
	{
		name: "cog",
		title: __("Cog", "ultimate-blocks"),
		type: "wordpress",
		icon: cog,
	},
	{
		name: "color",
		title: __("Color", "ultimate-blocks"),
		type: "wordpress",
		icon: color,
	},
	{
		name: "column",
		title: __("Column", "ultimate-blocks"),
		type: "wordpress",
		icon: column,
		categories: ["blocks"],
	},
	{
		name: "columns",
		title: __("Columns", "ultimate-blocks"),
		type: "wordpress",
		icon: columns,
		categories: ["blocks"],
	},
	{
		name: "comment",
		title: __("Comment", "ultimate-blocks"),
		type: "wordpress",
		icon: comment,
		categories: ["blocks"],
	},
	{
		name: "commentAuthorAvatar",
		title: __("Comment Author Avatar", "ultimate-blocks"),
		type: "wordpress",
		icon: commentAuthorAvatar,
		categories: ["blocks"],
	},
	{
		name: "commentAuthorName",
		title: __("Comment Author Name", "ultimate-blocks"),
		type: "wordpress",
		icon: commentAuthorName,
		categories: ["blocks"],
	},
	{
		name: "commentContent",
		title: __("Comment Content", "ultimate-blocks"),
		type: "wordpress",
		icon: commentContent,
		categories: ["blocks"],
	},
	{
		name: "commentEditLink",
		title: __("Comment Edit Link", "ultimate-blocks"),
		type: "wordpress",
		icon: commentEditLink,
		categories: ["blocks"],
	},
	{
		name: "commentReplyLink",
		title: __("Comment Reply Link", "ultimate-blocks"),
		type: "wordpress",
		icon: commentReplyLink,
		categories: ["blocks"],
	},
	{
		name: "cover",
		title: __("Cover", "ultimate-blocks"),
		type: "wordpress",
		icon: cover,
		categories: ["blocks"],
	},
	{
		name: "create",
		title: __("Create", "ultimate-blocks"),
		type: "wordpress",
		icon: create,
	},
	{
		name: "crop",
		title: __("Crop", "ultimate-blocks"),
		type: "wordpress",
		icon: crop,
	},
	{
		name: "currencyDollar",
		title: __("Currency Dollar", "ultimate-blocks"),
		type: "wordpress",
		icon: currencyDollar,
	},
	{
		name: "currencyEuro",
		title: __("Currency Euro", "ultimate-blocks"),
		type: "wordpress",
		icon: currencyEuro,
	},
	{
		name: "currencyPound",
		title: __("Currency Pound", "ultimate-blocks"),
		type: "wordpress",
		icon: currencyPound,
	},
	{
		name: "customPostType",
		title: __("Custom Post Type", "ultimate-blocks"),
		type: "wordpress",
		icon: customPostType,
	},
	{
		name: "desktop",
		title: __("Desktop", "ultimate-blocks"),
		type: "wordpress",
		icon: desktop,
		categories: ["devices"],
	},
	{
		name: "dragHandle",
		title: __("Drag Handle", "ultimate-blocks"),
		type: "wordpress",
		icon: dragHandle,
	},
	{
		name: "download",
		title: __("Download", "ultimate-blocks"),
		type: "wordpress",
		icon: download,
		categories: ["arrows"],
	},
	{
		name: "edit",
		title: __("Edit", "ultimate-blocks"),
		type: "wordpress",
		icon: edit,
	},
	{
		name: "external",
		title: __("External", "ultimate-blocks"),
		type: "wordpress",
		icon: external,
	},
	{
		name: "file",
		title: __("File", "ultimate-blocks"),
		type: "wordpress",
		icon: file,
	},
	{
		name: "flipHorizontal",
		title: __("Flip Horizontal", "ultimate-blocks"),
		type: "wordpress",
		icon: flipHorizontal,
	},
	{
		name: "flipVertical",
		title: __("Flip Vertical", "ultimate-blocks"),
		type: "wordpress",
		icon: flipVertical,
	},
	{
		name: "formatBold",
		title: __("Format Bold", "ultimate-blocks"),
		type: "wordpress",
		icon: formatBold,
		categories: ["editor"],
	},
	{
		name: "formatCapitalize",
		title: __("Format Capitalize", "ultimate-blocks"),
		type: "wordpress",
		icon: formatCapitalize,
		categories: ["editor"],
	},
	{
		name: "formatIndent",
		title: __("Format Indent", "ultimate-blocks"),
		type: "wordpress",
		icon: formatIndent,
		categories: ["editor"],
	},
	{
		name: "formatIndentRTL",
		title: __("Format Indent RTL", "ultimate-blocks"),
		type: "wordpress",
		icon: formatIndentRTL,
	},
	{
		name: "formatItalic",
		title: __("Format Italic", "ultimate-blocks"),
		type: "wordpress",
		icon: formatItalic,
		categories: ["editor"],
	},
	{
		name: "formatListBullets",
		title: __("Format List Bullets", "ultimate-blocks"),
		type: "wordpress",
		icon: formatListBullets,
		categories: ["editor"],
	},
	{
		name: "formatListBulletsRTL",
		title: __("Format List Bullets RTL", "ultimate-blocks"),
		type: "wordpress",
		icon: formatListBulletsRTL,
		categories: ["editor"],
	},
	{
		name: "formatListNumbered",
		title: __("Format List Numbered", "ultimate-blocks"),
		type: "wordpress",
		icon: formatListNumbered,
		categories: ["editor"],
	},
	{
		name: "formatListNumberedRTL",
		title: __("Format List Numbered RTL", "ultimate-blocks"),
		type: "wordpress",
		icon: formatListNumberedRTL,
		categories: ["editor"],
	},
	{
		name: "formatLtr",
		title: __("Format LTR", "ultimate-blocks"),
		type: "wordpress",
		icon: formatLtr,
		categories: ["editor"],
	},
	{
		name: "formatLowercase",
		title: __("Format Lowercase", "ultimate-blocks"),
		type: "wordpress",
		icon: formatLowercase,
		categories: ["editor"],
	},
	{
		name: "formatOutdent",
		title: __("Format Outdent", "ultimate-blocks"),
		type: "wordpress",
		icon: formatOutdent,
		categories: ["editor"],
	},
	{
		name: "formatOutdentRTL",
		title: __("Format Outdent RTL", "ultimate-blocks"),
		type: "wordpress",
		icon: formatOutdentRTL,
		categories: ["editor"],
	},
	{
		name: "formatRtl",
		title: __("Format RTL", "ultimate-blocks"),
		type: "wordpress",
		icon: formatRtl,
		categories: ["editor"],
	},
	{
		name: "formatStrikethrough",
		title: __("Format Strikethrough", "ultimate-blocks"),
		type: "wordpress",
		icon: formatStrikethrough,
		categories: ["editor"],
	},
	{
		name: "formatUnderline",
		title: __("Format Underline", "ultimate-blocks"),
		type: "wordpress",
		icon: formatUnderline,
		categories: ["editor"],
	},
	{
		name: "formatUppercase",
		title: __("Format Uppercase", "ultimate-blocks"),
		type: "wordpress",
		icon: formatUppercase,
		categories: ["editor"],
	},
	{
		name: "fullscreen",
		title: __("Fullscreen", "ultimate-blocks"),
		type: "wordpress",
		icon: fullscreen,
		categories: ["editor"],
	},
	{
		name: "gallery",
		title: __("Gallery", "ultimate-blocks"),
		type: "wordpress",
		icon: gallery,
		categories: ["blocks", "media"],
	},
	{
		name: "globe",
		title: __("Globe", "ultimate-blocks"),
		type: "wordpress",
		icon: globe,
	},
	{
		name: "grid",
		title: __("Grid", "ultimate-blocks"),
		type: "wordpress",
		icon: grid,
	},
	{
		name: "group",
		title: __("Group", "ultimate-blocks"),
		type: "wordpress",
		icon: group,
		categories: ["blocks"],
	},
	{
		name: "handle",
		title: __("Handle", "ultimate-blocks"),
		type: "wordpress",
		icon: handle,
	},
	{
		name: "heading",
		title: __("Heading", "ultimate-blocks"),
		type: "wordpress",
		icon: heading,
		categories: ["blocks"],
	},
	{
		name: "help",
		title: __("Help", "ultimate-blocks"),
		type: "wordpress",
		icon: help,
	},
	{
		name: "helpFilled",
		title: __("Help - Filled", "ultimate-blocks"),
		type: "wordpress",
		icon: helpFilled,
	},
	{
		name: "inbox",
		title: __("Inbox", "ultimate-blocks"),
		type: "wordpress",
		icon: inbox,
	},
	{
		name: "institution",
		title: __("Institution", "ultimate-blocks"),
		type: "wordpress",
		icon: institution,
	},
	{
		name: "home",
		title: __("Home", "ultimate-blocks"),
		type: "wordpress",
		icon: home,
		categories: ["blocks"],
	},
	{
		name: "html",
		title: __("HTML", "ultimate-blocks"),
		type: "wordpress",
		icon: html,
		categories: ["blocks"],
	},
	{
		isDefault: true,
		name: "image",
		title: __("Image", "ultimate-blocks"),
		type: "wordpress",
		icon: image,
		categories: ["blocks", "media"],
	},
	{
		name: "info",
		title: __("Info", "ultimate-blocks"),
		type: "wordpress",
		icon: info,
	},
	{
		name: "insertAfter",
		title: __("Insert After", "ultimate-blocks"),
		type: "wordpress",
		icon: insertAfter,
		categories: ["editor"],
	},
	{
		name: "insertBefore",
		title: __("Insert Before", "ultimate-blocks"),
		type: "wordpress",
		icon: insertBefore,
		categories: ["editor"],
	},
	{
		name: "justifyLeft",
		title: __("Justify Left", "ultimate-blocks"),
		type: "wordpress",
		icon: justifyLeft,
		categories: ["editor"],
	},
	{
		name: "justifyCenter",
		title: __("Justify Center", "ultimate-blocks"),
		type: "wordpress",
		icon: justifyCenter,
		categories: ["editor"],
	},
	{
		name: "justifyRight",
		title: __("Justify Right", "ultimate-blocks"),
		type: "wordpress",
		icon: justifyRight,
		categories: ["editor"],
	},
	{
		name: "justifySpaceBetween",
		title: __("Justify Space Between", "ultimate-blocks"),
		type: "wordpress",
		icon: justifySpaceBetween,
		categories: ["editor"],
	},
	{
		name: "key",
		title: __("Key", "ultimate-blocks"),
		type: "wordpress",
		icon: key,
	},
	{
		name: "keyboardClose",
		title: __("Keyboard Close", "ultimate-blocks"),
		type: "wordpress",
		icon: keyboardClose,
		categories: ["editor"],
	},
	{
		name: "keyboardReturn",
		title: __("Keyboard Return", "ultimate-blocks"),
		type: "wordpress",
		icon: keyboardReturn,
		categories: ["editor"],
	},
	{
		name: "layout",
		title: __("Layout", "ultimate-blocks"),
		type: "wordpress",
		icon: layout,
	},
	{
		name: "lifesaver",
		title: __("Lifesaver", "ultimate-blocks"),
		type: "wordpress",
		icon: lifesaver,
	},
	// There are some issues with these icons.
	// {
	// 	name: 'lineDashed',
	// 	title:  __( 'Line Dashed', 'ultimate-blocks' ),
	// 	type:"wordpress",
	// 	icon: lineDashed,
	// },
	// {
	// 	name: 'lineDotted',
	// 	title:  __( 'Line Dotted', 'ultimate-blocks' ),
	// 	type:"wordpress",
	// 	icon: lineDotted,
	// },
	// {
	// 	name: 'lineSolid',
	// 	title:  __( 'Line Solid', 'ultimate-blocks' ),
	// 	type:"wordpress",
	// 	icon: lineSolid,
	// },
	{
		name: "link",
		title: __("Link", "ultimate-blocks"),
		type: "wordpress",
		icon: link,
		categories: ["editor"],
	},
	{
		name: "linkOff",
		title: __("Link Off", "ultimate-blocks"),
		type: "wordpress",
		icon: linkOff,
		categories: ["editor"],
	},
	{
		name: "list",
		title: __("List", "ultimate-blocks"),
		type: "wordpress",
		icon: list,
		categories: ["blocks"],
	},
	{
		name: "listView",
		title: __("List View", "ultimate-blocks"),
		type: "wordpress",
		icon: listView,
		categories: ["editor"],
	},
	{
		name: "lock",
		title: __("Lock", "ultimate-blocks"),
		type: "wordpress",
		icon: lock,
		categories: ["editor"],
	},
	{
		name: "login",
		title: __("Login", "ultimate-blocks"),
		type: "wordpress",
		icon: login,
	},
	{
		name: "loop",
		title: __("Loop", "ultimate-blocks"),
		type: "wordpress",
		icon: loop,
		categories: ["blocks"],
	},
	{
		name: "mapMarker",
		title: __("Map Marker", "ultimate-blocks"),
		type: "wordpress",
		icon: mapMarker,
	},
	{
		name: "media",
		title: __("Media", "ultimate-blocks"),
		type: "wordpress",
		icon: media,
		categories: ["blocks", "media"],
	},
	{
		name: "mediaAndText",
		title: __("Media & Text", "ultimate-blocks"),
		type: "wordpress",
		icon: mediaAndText,
		categories: ["blocks", "media"],
	},
	{
		name: "megaphone",
		title: __("Megaphone", "ultimate-blocks"),
		type: "wordpress",
		icon: megaphone,
	},
	{
		name: "menu",
		title: __("Menu", "ultimate-blocks"),
		type: "wordpress",
		icon: menu,
	},
	{
		name: "mobile",
		title: __("Mobile", "ultimate-blocks"),
		type: "wordpress",
		icon: mobile,
		categories: ["devices"],
	},
	{
		name: "more",
		title: __("More", "ultimate-blocks"),
		type: "wordpress",
		icon: more,
	},
	{
		name: "moreHorizontal",
		title: __("More Horizontal", "ultimate-blocks"),
		type: "wordpress",
		icon: moreHorizontal,
	},
	{
		name: "moreHorizontalMobile",
		title: __("More Horizontal - Mobile", "ultimate-blocks"),
		type: "wordpress",
		icon: moreHorizontalMobile,
	},
	{
		name: "moreVertical",
		title: __("More Vertical", "ultimate-blocks"),
		type: "wordpress",
		icon: moreVertical,
	},
	{
		name: "moveTo",
		title: __("Move To", "ultimate-blocks"),
		type: "wordpress",
		icon: moveTo,
		categories: ["arrows"],
	},
	{
		name: "navigation",
		title: __("Navigation", "ultimate-blocks"),
		type: "wordpress",
		icon: navigation,
	},
	{
		name: "overlayText",
		title: __("Overlay Text", "ultimate-blocks"),
		type: "wordpress",
		icon: overlayText,
	},
	{
		name: "pageBreak",
		title: __("Page Break", "ultimate-blocks"),
		type: "wordpress",
		icon: pageBreak,
	},
	{
		name: "customLink",
		title: __("Custom Link", "ultimate-blocks"),
		type: "wordpress",
		icon: customLink,
	},
	{
		name: "page",
		title: __("Page", "ultimate-blocks"),
		type: "wordpress",
		icon: page,
	},
	{
		name: "pages",
		title: __("Pages", "ultimate-blocks"),
		type: "wordpress",
		icon: pages,
	},
	{
		name: "paragraph",
		title: __("Paragraph", "ultimate-blocks"),
		type: "wordpress",
		icon: paragraph,
	},
	{
		name: "payment",
		title: __("Payment", "ultimate-blocks"),
		type: "wordpress",
		icon: payment,
	},
	{
		name: "percent",
		title: __("Percent", "ultimate-blocks"),
		type: "wordpress",
		icon: percent,
	},
	{
		name: "positionCenter",
		title: __("Position Center", "ultimate-blocks"),
		type: "wordpress",
		icon: positionCenter,
	},
	{
		name: "positionLeft",
		title: __("Position Left", "ultimate-blocks"),
		type: "wordpress",
		icon: positionLeft,
	},
	{
		name: "positionRight",
		title: __("Position Right", "ultimate-blocks"),
		type: "wordpress",
		icon: positionRight,
	},
	{
		name: "post",
		title: __("Post", "ultimate-blocks"),
		type: "wordpress",
		icon: post,
	},
	{
		name: "pencil",
		title: __("Pencil", "ultimate-blocks"),
		type: "wordpress",
		icon: pencil,
	},
	{
		name: "people",
		title: __("People", "ultimate-blocks"),
		type: "wordpress",
		icon: people,
	},
	{
		name: "pin",
		title: __("Pin", "ultimate-blocks"),
		type: "wordpress",
		icon: pin,
	},
	{
		name: "plugins",
		title: __("Plugins", "ultimate-blocks"),
		type: "wordpress",
		icon: plugins,
	},
	{
		name: "plusCircleFilled",
		title: __("Plus Circle - Filled", "ultimate-blocks"),
		type: "wordpress",
		icon: plusCircleFilled,
	},
	{
		name: "plusCircle",
		title: __("Plus Circle", "ultimate-blocks"),
		type: "wordpress",
		icon: plusCircle,
	},
	{
		name: "plus",
		title: __("Plus", "ultimate-blocks"),
		type: "wordpress",
		icon: plus,
	},
	{
		name: "postAuthor",
		title: __("Post Author", "ultimate-blocks"),
		type: "wordpress",
		icon: postAuthor,
		categories: ["blocks"],
	},
	{
		name: "postCategories",
		title: __("Post Categories", "ultimate-blocks"),
		type: "wordpress",
		icon: postCategories,
		categories: ["blocks"],
	},
	{
		name: "postContent",
		title: __("Post Content", "ultimate-blocks"),
		type: "wordpress",
		icon: postContent,
		categories: ["blocks"],
	},
	{
		name: "postComments",
		title: __("Post Comments", "ultimate-blocks"),
		type: "wordpress",
		icon: postComments,
		categories: ["blocks"],
	},
	{
		name: "postCommentsCount",
		title: __("Post Comment Count", "ultimate-blocks"),
		type: "wordpress",
		icon: postCommentsCount,
	},
	{
		name: "postCommentsForm",
		title: __("Post Comments Form", "ultimate-blocks"),
		type: "wordpress",
		icon: postCommentsForm,
		categories: ["blocks"],
	},
	{
		name: "postDate",
		title: __("Post Date", "ultimate-blocks"),
		type: "wordpress",
		icon: postDate,
		categories: ["blocks"],
	},
	{
		name: "postExcerpt",
		title: __("Post Excerpt", "ultimate-blocks"),
		type: "wordpress",
		icon: postExcerpt,
		categories: ["blocks"],
	},
	{
		name: "postFeaturedImage",
		title: __("Post Featured Image", "ultimate-blocks"),
		type: "wordpress",
		icon: postFeaturedImage,
		categories: ["blocks"],
	},
	{
		name: "postList",
		title: __("Post List", "ultimate-blocks"),
		type: "wordpress",
		icon: postList,
		categories: ["blocks"],
	},
	{
		name: "postTerms",
		title: __("Post Terms", "ultimate-blocks"),
		type: "wordpress",
		icon: postTerms,
		categories: ["blocks"],
	},
	{
		name: "previous",
		title: __("Previous", "ultimate-blocks"),
		type: "wordpress",
		icon: previous,
		categories: ["arrows"],
	},
	{
		name: "next",
		title: __("Next", "ultimate-blocks"),
		type: "wordpress",
		icon: next,
		categories: ["arrows"],
	},
	{
		name: "preformatted",
		title: __("Preformatted", "ultimate-blocks"),
		type: "wordpress",
		icon: preformatted,
	},
	{
		name: "pullLeft",
		title: __("Pull Left", "ultimate-blocks"),
		type: "wordpress",
		icon: pullLeft,
	},
	{
		name: "pullRight",
		title: __("Pull Right", "ultimate-blocks"),
		type: "wordpress",
		icon: pullRight,
	},
	{
		name: "pullquote",
		title: __("Pull Quote", "ultimate-blocks"),
		type: "wordpress",
		icon: pullquote,
	},
	{
		name: "queryPagination",
		title: __("Query Pagination", "ultimate-blocks"),
		type: "wordpress",
		icon: queryPagination,
	},
	{
		name: "queryPaginationNext",
		title: __("Query Pagination Next", "ultimate-blocks"),
		type: "wordpress",
		icon: queryPaginationNext,
		categories: ["arrows"],
	},
	{
		name: "queryPaginationNumbers",
		title: __("Query Pagination Numbers", "ultimate-blocks"),
		type: "wordpress",
		icon: queryPaginationNumbers,
	},
	{
		name: "queryPaginationPrevious",
		title: __("Query Pagination Previous", "ultimate-blocks"),
		type: "wordpress",
		icon: queryPaginationPrevious,
		categories: ["arrows"],
	},
	{
		name: "quote",
		title: __("Quote", "ultimate-blocks"),
		type: "wordpress",
		icon: quote,
		categories: ["blocks"],
	},
	{
		name: "receipt",
		title: __("Receipt", "ultimate-blocks"),
		type: "wordpress",
		icon: receipt,
	},
	{
		name: "redo",
		title: __("Redo", "ultimate-blocks"),
		type: "wordpress",
		icon: redo,
		categories: ["arrows", "editor"],
	},
	{
		name: "removeBug",
		title: __("Remove Bug", "ultimate-blocks"),
		type: "wordpress",
		icon: removeBug,
	},
	{
		name: "removeSubmenu",
		title: __("Remove Submenu", "ultimate-blocks"),
		type: "wordpress",
		icon: removeSubmenu,
	},
	{
		name: "replace",
		title: __("Replace", "ultimate-blocks"),
		type: "wordpress",
		icon: replace,
		categories: ["arrows"],
	},
	{
		name: "reset",
		title: __("Reset", "ultimate-blocks"),
		type: "wordpress",
		icon: reset,
		categories: ["minus"],
	},
	{
		name: "resizeCornerNE",
		title: __("Resize Corner", "ultimate-blocks"),
		type: "wordpress",
		icon: resizeCornerNE,
		categories: ["arrows"],
	},
	{
		name: "reusableBlock",
		title: __("Reusable Block", "ultimate-blocks"),
		type: "wordpress",
		icon: reusableBlock,
		categories: ["arrows"],
	},
	{
		name: "rotateLeft",
		title: __("Rotate Left", "ultimate-blocks"),
		type: "wordpress",
		icon: rotateLeft,
		categories: ["arrows"],
	},
	{
		name: "rotateRight",
		title: __("Rotate Right", "ultimate-blocks"),
		type: "wordpress",
		icon: rotateRight,
		categories: ["arrows"],
	},
	{
		name: "row",
		title: __("Row", "ultimate-blocks"),
		type: "wordpress",
		icon: row,
	},
	{
		name: "rss",
		title: __("RSS", "ultimate-blocks"),
		type: "wordpress",
		icon: rss,
	},
	{
		name: "search",
		title: __("Search", "ultimate-blocks"),
		type: "wordpress",
		icon: search,
		categories: ["magnifying glass"],
	},
	{
		name: "separator",
		title: __("Separator", "ultimate-blocks"),
		type: "wordpress",
		icon: separator,
		categories: ["blocks"],
	},
	{
		name: "settings",
		title: __("Settings", "ultimate-blocks"),
		type: "wordpress",
		icon: settings,
	},
	{
		name: "share",
		title: __("Share", "ultimate-blocks"),
		type: "wordpress",
		icon: share,
	},
	{
		name: "shield",
		title: __("Shield", "ultimate-blocks"),
		type: "wordpress",
		icon: shield,
	},
	{
		name: "shortcode",
		title: __("Shortcode", "ultimate-blocks"),
		type: "wordpress",
		icon: shortcode,
		categories: ["blocks"],
	},
	{
		name: "siteLogo",
		title: __("Site Logo", "ultimate-blocks"),
		type: "wordpress",
		icon: siteLogo,
		categories: ["blocks", "media"],
	},
	{
		isDefault: true,
		name: "sparkles",
		title: __("Sparkles", "ultimate-blocks"),
		type: "wordpress",
		icon: sparkles,
	},
	{
		name: "stack",
		title: __("Stack", "ultimate-blocks"),
		type: "wordpress",
		icon: stack,
	},
	{
		name: "starEmpty",
		title: __("Star Empty", "ultimate-blocks"),
		type: "wordpress",
		icon: starEmpty,
	},
	{
		name: "starFilled",
		title: __("Star Filled", "ultimate-blocks"),
		type: "wordpress",
		icon: starFilled,
	},
	{
		name: "starHalf",
		title: __("Star Half", "ultimate-blocks"),
		type: "wordpress",
		icon: starHalf,
	},
	{
		name: "store",
		title: __("Store", "ultimate-blocks"),
		type: "wordpress",
		icon: store,
	},
	{
		name: "stretchFullWidth",
		title: __("Stretch Full Width", "ultimate-blocks"),
		type: "wordpress",
		icon: stretchFullWidth,
		categories: ["editor"],
	},
	{
		name: "styles",
		title: __("Styles", "ultimate-blocks"),
		type: "wordpress",
		icon: styles,
	},
	{
		isDefault: true,
		name: "shipping",
		title: __("Shipping", "ultimate-blocks"),
		type: "wordpress",
		icon: shipping,
		categories: ["truck"],
	},
	{
		name: "stretchWide",
		title: __("Stretch Wide", "ultimate-blocks"),
		type: "wordpress",
		icon: stretchWide,
		categories: ["editor"],
	},
	{
		name: "subscript",
		title: __("Subscript", "ultimate-blocks"),
		type: "wordpress",
		icon: subscript,
		categories: ["editor"],
	},
	{
		name: "superscript",
		title: __("Superscript", "ultimate-blocks"),
		type: "wordpress",
		icon: superscript,
		categories: ["editor"],
	},
	{
		name: "swatch",
		title: __("Swatch", "ultimate-blocks"),
		type: "wordpress",
		icon: swatch,
	},
	{
		name: "symbol",
		title: __("Symbol", "ultimate-blocks"),
		type: "wordpress",
		icon: symbol,
	},
	{
		name: "symbolFilled",
		title: __("Symbol - Filled", "ultimate-blocks"),
		type: "wordpress",
		icon: symbolFilled,
	},
	{
		name: "tableColumnAfter",
		title: __("Table Column After", "ultimate-blocks"),
		type: "wordpress",
		icon: tableColumnAfter,
		categories: ["editor"],
	},
	{
		name: "tableColumnBefore",
		title: __("Table Column Before", "ultimate-blocks"),
		type: "wordpress",
		icon: tableColumnBefore,
		categories: ["editor"],
	},
	{
		name: "tableColumnDelete",
		title: __("Table Column Delete", "ultimate-blocks"),
		type: "wordpress",
		icon: tableColumnDelete,
		categories: ["editor"],
	},
	{
		name: "tableRowAfter",
		title: __("Table Row After", "ultimate-blocks"),
		type: "wordpress",
		icon: tableRowAfter,
		categories: ["editor"],
	},
	{
		name: "tableRowBefore",
		title: __("Table Row Before", "ultimate-blocks"),
		type: "wordpress",
		icon: tableRowBefore,
		categories: ["editor"],
	},
	{
		name: "tableRowDelete",
		title: __("Table Row Delete", "ultimate-blocks"),
		type: "wordpress",
		icon: tableRowDelete,
		categories: ["editor"],
	},
	{
		name: "table",
		title: __("Table", "ultimate-blocks"),
		type: "wordpress",
		icon: table,
	},
	{
		name: "tag",
		title: __("Tag", "ultimate-blocks"),
		type: "wordpress",
		icon: tag,
	},
	{
		name: "termDescription",
		title: __("Term Description", "ultimate-blocks"),
		type: "wordpress",
		icon: termDescription,
		categories: ["blocks"],
	},
	{
		name: "footer",
		title: __("Footer", "ultimate-blocks"),
		type: "wordpress",
		icon: footer,
	},
	{
		name: "header",
		title: __("Header", "ultimate-blocks"),
		type: "wordpress",
		icon: header,
	},
	{
		name: "sidebar",
		title: __("Sidebar", "ultimate-blocks"),
		type: "wordpress",
		icon: sidebar,
	},
	{
		name: "textColor",
		title: __("Text Color", "ultimate-blocks"),
		type: "wordpress",
		icon: textColor,
	},
	{
		name: "tablet",
		title: __("Tablet", "ultimate-blocks"),
		type: "wordpress",
		icon: tablet,
		categories: ["devices"],
	},
	{
		name: "title",
		title: __("Title", "ultimate-blocks"),
		type: "wordpress",
		icon: title,
	},
	{
		name: "tip",
		title: __("Tip", "ultimate-blocks"),
		type: "wordpress",
		icon: tip,
	},
	{
		name: "tool",
		title: __("Tool", "ultimate-blocks"),
		type: "wordpress",
		icon: tool,
	},
	{
		name: "trash",
		title: __("Trash", "ultimate-blocks"),
		type: "wordpress",
		icon: trash,
	},
	{
		name: "trendingDown",
		title: __("Trending Down", "ultimate-blocks"),
		type: "wordpress",
		icon: trendingDown,
		categories: ["arrows"],
	},
	{
		name: "trendingUp",
		title: __("Trending Up", "ultimate-blocks"),
		type: "wordpress",
		icon: trendingUp,
		categories: ["arrows"],
	},
	{
		name: "typography",
		title: __("Typography", "ultimate-blocks"),
		type: "wordpress",
		icon: typography,
	},
	{
		name: "undo",
		title: __("Undo", "ultimate-blocks"),
		type: "wordpress",
		icon: undo,
		categories: ["arrows", "editor"],
	},
	{
		name: "ungroup",
		title: __("Ungroup", "ultimate-blocks"),
		type: "wordpress",
		icon: ungroup,
		categories: ["editor"],
	},
	{
		name: "unlock",
		title: __("Unlock", "ultimate-blocks"),
		type: "wordpress",
		icon: unlock,
		categories: ["editor"],
	},
	{
		name: "update",
		title: __("Update", "ultimate-blocks"),
		type: "wordpress",
		icon: update,
	},
	{
		name: "upload",
		title: __("Upload", "ultimate-blocks"),
		type: "wordpress",
		icon: upload,
		categories: ["arrows"],
	},
	{
		isDefault: true,
		name: "verse",
		title: __("Verse", "ultimate-blocks"),
		type: "wordpress",
		icon: verse,
		categories: ["blocks"],
	},
	{
		name: "video",
		title: __("Video", "ultimate-blocks"),
		type: "wordpress",
		icon: video,
		categories: ["media"],
	},
	{
		name: "warning",
		title: __("Warning", "ultimate-blocks"),
		type: "wordpress",
		icon: warning,
	},
	{
		name: "widget",
		title: __("Widget", "ultimate-blocks"),
		type: "wordpress",
		icon: widget,
	},
];

export const ultimateIcons = [
	{
		isDefault: false,
		type: "wordpress",
		title: __("WordPress", "ultimate-blocks"),
		icons: [...wordpressSocialIcons, ...wordpressIcons],
		categories: [
			{
				name: "arrows",
				title: __("Arrows", "ultimate-blocks"),
			},
			{
				name: "blocks",
				title: __("Blocks", "ultimate-blocks"),
			},
			{
				name: "devices",
				title: __("Devices", "ultimate-blocks"),
			},
			{
				name: "editor",
				title: __("Editor", "ultimate-blocks"),
			},
			{
				name: "logos",
				title: __("Logos", "ultimate-blocks"),
			},
			{
				name: "media",
				title: __("Media", "ultimate-blocks"),
			},
		],
	},
	{
		isDefault: false,
		type: "font-awesome",
		title: __("Font Awesome", "ultimate-blocks"),
		icons: fontAwesomeIcons,
		categories: fontAwesomeCategories,
	},
];
