name: JS Tests

on:
  workflow_call:


jobs:
  js-tests:
    name: JS Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm ci -f

      - name: Run JS tests
        run: npm test
