name: Production Build

on:
  push:
    branches: [ "55-github-actions-failure-from-master" ]

jobs:
  server-setup:
    uses: ./.github/workflows/server-setup-template.yml

  build:
    if: github.event_type != 'pull_request'
    needs: [ server-setup ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm ci -f

      - name: Build JS
        run: npm run build
