name: Production Build

on:
  push:
    branches: [ ci-integration ]
  pull_request:
    branches: [ ci-integration ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'production build'
